### ISSUE TITLE
webp not showing

### ISSUE THREAD

**Issue by GMTeams** [postyou/contao-webp-bundle#1]
I've installed this nice plugin and activated the option in the contao setting. But all my images are shown in jpeg/png as before. I've cleaned the image cache in contao and in my browser. On my server the packages "gd" and "imagick" are installed.
Do you know what I can do? Thanks.

**Comment by theDyingMountain** [comment]
Can you see if webp is enabled in these packages? If yes, maybe it depends on [rosell-dk/webp-convert](https://github.com/rosell-dk/webp-convert) lib, which I'm using for the conversation.

**Comment by GMTeams** [comment]
Thx for your help. I did some research and it seems that my provider DF is not supporting webp via GD.
