### ISSUE TITLE
Adding Rocksolid Custom Elements

### ISSUE THREAD

**Issue by Kyuhunter** [postyou/contao-webp-bundle#2]
Is it possible to add custom elements created with eiter Rocksolid Custom Elements or Premium Contao Themes Custom Elements to the list of converted Elements?

**Comment by theDyingMountain** [comment]
Since Contao 4.8 the webp functionality is implemented in the core, I think this bundle isn't necessary anymore.

**Comment by Kyuhunter** [comment]
Since we are on the 4.4 LTS Version this doesnt solve my problem sadly. 
Is there now way to add the custom elements?

I figured out how to create a webp image in the template, but having this be done automatically would be nice.

**Comment by theDyingMountain** [comment]
Sorry in a few days the next LTS Version (4.9) will be released. I think this feature will be used by very few users. Costs and benefits are out of proportion.
