### ISSUE TITLE
installed, activated, but isn´t doin anything

### ISSUE THREAD

**Issue by olivergrosche** [postyou/contao-webp-bundle#7]
pictures are still in jpg format under chrome. is there anything im missin?

**Comment by theDyingMountain** [comment]
maybe your server doesn't support webp conversation?

**Comment by AgenceUpMotion** [comment]
> pictures are still in jpg format under chrome. is there anything im missin?

Same for me on a Contao 4.9.13. gd is installed on my server

**Comment by AgenceUpMotion** [comment]
gd is installed on my server

**Comment by theDyingMountain** [comment]
Maybe you PHP configuration doesn't include the webp plugin? But since 4.9 webp is supported in the contao core, you don't need this plugin.

**Comment by AgenceUpMotion** [comment]
Thanks, I'll take a look at PHP. gd is enough for it to work?
I saw yes that we could convert the images in Themes> Images, but I never used this function and I cannot find info on how to use it

**Comment by theDyingMountain** [comment]
GD is enough if you PHP and webserver support it.
For the core function you have to set Imagesizes under Themes and set these imagesizes on the images in the content elements.

**Comment by AgenceUpMotion** [comment]
Ok it works, a bit boring to make a size for each image .. That's why I wanted to use your module.

**Comment by theDyingMountain** [comment]
Okay cool! I use the image size function in every web project. Otherwise, it's not possible to generate small images for mobile devices.
